steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'functions/autodeploy'
- name: 'gcr.io/cloud-builders/npm'
  args: ['test']
  dir: 'functions/autodeploy'
- name: 'ubuntu'
  args: ['ls', '-lisah']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'functions', 'deploy', 'quickdraw-predict', '--region=europe-west1', '--trigger-http']